services:
  - type: web
    name: fishing-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: CHANNEL_ID
        value: "-1002458862246"
      - key: CHAT_ID
        value: "-1001790011004"
      - key: THREAD_ID
        value: "15708"